resource "digitalocean_database_cluster" "power_map" {
  name                 = "co-pm-db-1"
  engine               = "pg"
  version              = "16"
  size                 = var.cluster_size
  region               = var.region
  node_count           = 1
  private_network_uuid = digitalocean_vpc.power_map.id
}

# ── Databases ────────────────────────────────────────────────────────────────

resource "digitalocean_database_db" "production" {
  cluster_id = digitalocean_database_cluster.power_map.id
  name       = "co_pm_db_production"
}

resource "digitalocean_database_db" "test" {
  cluster_id = digitalocean_database_cluster.power_map.id
  name       = "co_pm_db_test"
}

# ── Users ─────────────────────────────────────────────────────────────────────
# Passwords are auto-generated by DO and surfaced via outputs.tf.
# Object-level grants (DML-only for production_user, DDL for migrations,
# full access for test_user) are applied by scripts/write-db-secrets.sh
# after first apply, using the migrations user to run apply_schema.

resource "digitalocean_database_user" "production_user" {
  cluster_id = digitalocean_database_cluster.power_map.id
  name       = "co_pm_db_production_user"
}

resource "digitalocean_database_user" "production_migrations" {
  cluster_id = digitalocean_database_cluster.power_map.id
  name       = "co_pm_db_production_migrations"
}

resource "digitalocean_database_user" "test_user" {
  cluster_id = digitalocean_database_cluster.power_map.id
  name       = "co_pm_db_test_user"
}
