"""Generate the WA legislative seat-Role seed JSON from the jurisdictions seed (#263).

For each `legislative_district` jurisdiction (`usa-wa-ld-{N}`) emit three seats,
in LD-number order:
  - 1 Senate seat  — role_type `state_senator`, no qualifier
  - 2 House seats  — role_type `state_representative`, qualifier "Position 1" / "Position 2"

Chamber is referenced by the `org_wa_legislature_chamber` identifier value
(`usa_wa_senate` / `usa_wa_house`); jurisdiction by slug; role_type by slug.
Deterministic and DB-free — the committed output is the importable seed artifact
consumed by `scripts/seed_role_seats.py`.

Usage:
    uv run python -m scripts.generate_wa_seats <jurisdictions.json> [-o <out.json>]
"""

import argparse
import json
import re
from pathlib import Path
from typing import Any

from src.core.logging import configure_logging, get_logger

logger = get_logger(__name__)

_LD_SLUG_RE = re.compile(r"^usa-wa-ld-(\d+)$")


def _ld_number(slug: str) -> int:
    """Return the LD number from a `usa-wa-ld-{N}` slug, or raise ValueError."""
    m = _LD_SLUG_RE.match(slug)
    if m is None:
        raise ValueError(f"legislative_district slug not in usa-wa-ld-N form: {slug!r}")
    return int(m.group(1))


def generate_seats(jurisdictions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return the seat rows (Senate + House Position 1/2 per LD), in LD-number order."""
    lds = sorted(
        (_ld_number(j["slug"]), j["slug"])
        for j in jurisdictions
        if j.get("type") == "legislative_district"
    )
    seats: list[dict[str, Any]] = []
    for n, slug in lds:
        seats.append(
            {
                "chamber": "usa_wa_senate",
                "role_type": "state_senator",
                "jurisdiction_slug": slug,
                "qualifier": None,
                "title": f"Washington State Senator, LD-{n}",
            }
        )
        for pos in (1, 2):
            seats.append(
                {
                    "chamber": "usa_wa_house",
                    "role_type": "state_representative",
                    "jurisdiction_slug": slug,
                    "qualifier": f"Position {pos}",
                    "title": f"Washington State Representative, LD-{n}, Position {pos}",
                }
            )
    return seats


def build_seed(jurisdictions: list[dict[str, Any]]) -> dict[str, Any]:
    """Wrap generated seats in the seed-file envelope (_comment + seats)."""
    seats = generate_seats(jurisdictions)
    n_senate = sum(1 for s in seats if s["chamber"] == "usa_wa_senate")
    n_house = sum(1 for s in seats if s["chamber"] == "usa_wa_house")
    return {
        "_comment": (
            f"{len(seats)} WA legislative seat-Roles (#263): "
            f"{n_senate} Senate (1/LD) + {n_house} House (2/LD, Position 1/2). "
            "chamber -> org_wa_legislature_chamber identifier; jurisdiction -> slug; "
            "role_type -> slug. Generated by scripts/generate_wa_seats.py; imported by "
            "scripts/seed_role_seats.py."
        ),
        "seats": seats,
    }


def main() -> None:
    configure_logging()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("jurisdictions_file", type=Path, help="Path to the jurisdictions seed JSON")
    parser.add_argument(
        "-o",
        "--out",
        type=Path,
        default=None,
        help="Output path for the seats seed JSON (default: stdout)",
    )
    args = parser.parse_args()

    if not args.jurisdictions_file.exists():
        raise SystemExit(f"jurisdictions seed file not found: {args.jurisdictions_file}")

    jurisdictions = json.loads(args.jurisdictions_file.read_text()).get("jurisdictions", [])
    seed = build_seed(jurisdictions)
    text = json.dumps(seed, indent=2, ensure_ascii=False) + "\n"

    if args.out is None:
        print(text, end="")
    else:
        args.out.write_text(text)
        logger.info("Wrote %d seats to %s", len(seed["seats"]), args.out)


if __name__ == "__main__":
    main()
